### ISSUE TITLE
No 'Access-Control-Allow-Origin' header?

### ISSUE THREAD

**Issue by Digizard** [simplydallas/udacityreviewparser#2]
Heya Dallas,

The Udacity Review Queue is working just fine for me, but the Parser here seems to be hitting an issue. In starting it up, it loads for a while before saying

> OOPS! The tool failed to get usable JSON from Udacity based on your token. Try checking your token and trying again.

This is what's appearing in the console:
![screenshot 2016-06-09 at 10 13 47 am](https://cloud.githubusercontent.com/assets/2101199/15932778/eee813a2-2e2a-11e6-8fb4-7ba7b68d1cb4.png)

Usually, I just load the API access token after starting up the URQ, since it's already saved (as last used). Tried pasting it directly too, but still no dice.

Things seem to be loading slow for Udacity for me at the moment, so I don't know if that's related to the issue. It was working fine yesterday, though updating rather slowly.

**Comment by Digizard** [comment]
Oh, yeah, must've been something on Udacity's end. It's working fine now.

Of course, it works after I get around to writing this, haha. :laughing:

**Comment by simplydallas** [comment]
@SittingFox, I was going to suggest making sure the token didn't expire but I do know there was a little downtime at Udacity that probably caused it.  Glad to hear it is working again without too big of a gap for you!
